# Generated by Django 4.2.5 on 2023-09-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daangn_app', '0002_userinfo_delete_customuser_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
