# Generated by Django 4.2.5 on 2023-09-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daangn_app', '0006_user_alter_post_author_alter_userinfo_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='chat_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
