# Generated by Django 4.2.5 on 2023-09-26 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daangn_app', '0009_alter_chatroom_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
    ]
