# Generated by Django 4.2.5 on 2023-09-27 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daangn_app', '0013_userinfo_location_verified_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='location_verified',
            new_name='location_certified',
        ),
    ]
