# Generated by Django 4.2.5 on 2023-10-01 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daangn_app', '0013_alter_post_author'),
        ('daangn_app', '0015_user_location_user_location_certified_user_nickname_and_more'),
    ]

    operations = [
    ]
