# Generated by Django 4.2.5 on 2023-10-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daangn_app', '0016_merge_20231001_1521'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postimage',
            table=None,
        ),
    ]
