# Generated by Django 4.2.5 on 2023-10-02 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daangn_app', '0019_alter_postimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
