# Generated by Django 4.2.5 on 2023-10-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daangn_app', '0020_alter_chatroom_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
