# Generated by Django 4.2.5 on 2023-10-05 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daangn_app', '0022_alter_chatroom_created_at_disconnectinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ai_chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ai_ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sender', models.PositiveIntegerField()),
                ('send_at', models.DateTimeField(auto_now_add=True)),
                ('chatroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daangn_app.ai_chatroom')),
            ],
        ),
    ]
